### ISSUE TITLE
iOS : Image/animation missing on what-we-do

### ISSUE THREAD

**Issue by janos021** [ALASdoo/alasdoo_com_v2#1]
Steps to reproduce:
- Open https://alas-v2.netlify.app/
- Tap hamburger menu
- Tap What we do
- Scroll to "Providing full software quality assurance"
- Check layout
Actual error : image/animation missing above the "Providing full software quality assurance"
Expected fix : image/animation should load

Noticed on iPhone 11/iOS 16.03 - Safari 

Screenshot: https://drive.google.com/file/d/1HyaD4tR6suuu41-4l4u7ITjd_RFDaE6s/view

**Comment by vsomogyi** [comment]
No longer relevant. Closing
