### ISSUE TITLE
Safari: Unnecessary grey space is present on the Clients page

### ISSUE THREAD

**Issue by Qtester94** [ALASdoo/alasdoo_com_v2#10]
**Steps to reproduce:**
- Open the https://alas-v2.netlify.app/ page
- Click on the "Who we are" top navigation option
- Click on the "Clients" dropdown option
- Check the first paragraph

**Actual error:** Unnecessary grey space is present.
**Expected fix:** The grey space should be smaller.

**Noticed on:** macOS Ventura 13.3.1 - Safari 16.4

**Screencast:**
https://drive.google.com/file/d/13FeAr9oJBm_OgYP14hVgHhQ8oT_UJay8/view?usp=drivesdk

**Comment by lsale98** [comment]
Fixed, need to test on windows devices
