### ISSUE TITLE
The "Contact Us" menu item is not visible 

### ISSUE THREAD

**Issue by nemain00** [ALASdoo/alasdoo_com_v2#112]
The "Contact us" menu item is not visible when using resize extension and setting the resolution to 1366x768 and zooming in to 200%.
Screenshot:
https://drive.google.com/file/d/1fJGrhwVebGUYFcf1NUhmDh05_z2sdBUg/view?usp=sharing

![chrome_YeVNZKrJmk](https://github.com/user-attachments/assets/f104b86d-1a70-495d-9952-bcdd918bddeb)

**Comment by TheKolega** [comment]
Looks good :green_circle:, tested with chrome device toolbar 200% zoom
