### ISSUE TITLE
Typos in text

### ISSUE THREAD

**Issue by Tajana-Somogyi** [ALASdoo/alasdoo_com_v2#134]
"How to incorporate QA into software development process?" article:

- [x] inhouse to "in-house"

**Comment by nemain00** [comment]
- Spell checker issue for , 
	We encourage people to have a healthy work/life balance, and devote time and energy to their families and hobbies. on the alas page
	
-Izabrati izmedju ove dve recenice. --> alas doo
	Our top focus is writing a code that meets the highest standards. At the same time, our quality assurance team has the skills and experience to ensure that the software satisfies the strictest criteria.
	Our top focus is writing a code that meets the highest standards, while our quality assurance team has the skills and experience to ensure that the software satisfies the strictest criteria 
	
- prepraviti text sa jedan na dva --> our story
	Although the company has significantly grown, it has still kept its non‑corporate, people‑focused approach, home‑like atmosphere, and family values at its core
	Although the company has grown significantly, it still keeps its non‑corporate, people‑focused approach, home‑like atmosphere, and family values at its core
	
- Ukloniti zarez posle potential --> alas doo
	We are here to guide them on their road to success, empower them to reach their full potential, and shift to a growth mindset
	
- Prepraviti dodati our ispred relatonships --> our clients
	we do are reflected in relationships with our clients
	
- izabrati izmedju dve recenice --> our story
	Every change is met by an adequate organization and a period of adaptation, taking care that the quality of work is not affected.
	Every change is met by an adequate organization and a period of adaptation, ensuring the quality of work is not affected.
	
- Ukloniti zarez posle zrenjnain --> our-story
	developers in Zrenjanin and founded the company that has become the symbol of change, a synonym of 
	
- Seyshelles on clients locations tu ima za Seyshelles typo treba Seychelles --> clients loacation

- Ensure treba staviti umesto assure --> trusted-crypto-products-exchange-platform-for
	We performed system and acceptance testing to assure that the system was functioning as expected and met the client’s requirements.

- Proveriti za assure i gives umesto gave --> ensuring-user-trust-and-satisfaction-through-complete-testing-of
	multiple scenarios to assure they are carried over to the client’s e‑mail correctly. After confirmatory and investigative testing gave adequate results, a complete 

- Ispraviti duplo our our --> our team
We are always looking for candidates who share our our values and goals. If you recognize yourself in them, we are a great match.
	
- staviti an umesto a As a exchange platform --> trusted-crypto-products-exchange-platform-for
	As a exchange platform, the client had to make sure that their system’s features and functionality were working correctly to provide their customers with fast and reliable access to the markets. At the same time, they had to prioritize the security of their customers’ funds and personal information.
	
- promeniti na clients umesto client --> helping-digital-consumer-intelligence-leader-with-skills-gap
	We specialize in writing automation test cases for REST and RPC APIs, as well as other event‑driven backend services. By performing regular performance testing on backend services, we help our client ensure that their application is running efficiently and that it can handle a high volume of requests, thereby improving the user experience and minimizing the risk of issues or downtime.
	
- Internet treba da bude velikim --> a-15-year-long-partnership-in-building-a-robust-and-scalable-website-creation-tool
	Industry: Information and internet
	
- Pogledati social media icons sa screen readerom

- promeniti u ensure --> streamlining-carpooling
	How do we assure that only trusted drivers can participate in the carpool?

- on a day to day treba dodati a --> ensuring-that-the-patients-plans-for-the-future-are-safe-and-sound
	Mainly, patients’ privacy and data security are priorities that have to be guaranteed on day‑to‑day bases.
	
- treba promeniti u develop --> the-all-in-one-cannabis-dispensary-and-end-users-solution
	During the testing process, we improved existing and developed new test cases 
	
- dodati a ispred desktop --> the-all-in-one-cannabis-dispensary-and-end-users-solution
	We performed manual testing of the web application on desktop

-  Dodati the ispred USA --> the-all-in-one-cannabis-dispensary-and-end-users-solution
	Its modern interface is designed to help dispensaries all over USA work more

- razmak fali na on to
	ensuring that each feature was thoroughly tested before moving onto the next phase.

- Staviti the ispred software --> articles 
	How to incorporate QA into software development process?

- Staviti the ispred software --> how-to-choose-the-right-it-outsourcing-provider 
	How to incorporate QA into software development process?

- Staviti the ispred software --> how-to-choose-the-right-it-outsourcing-provider 
	How to incorporate QA into software development process?

- Staviti at alas --> 8-most-important-reasons-why-co
	We, in ALAS, always keep up to

- staviti the ispred software --> 8-most-important-reasons-why-co
	Learn how to incorporate QA into software development process.

-  staviti coffy shop ne caffe --> how-to-incorporate-qa-into-software-development-process
	coffee in a caffee shop.
	
-	Collaborate fali l --> what-is-the-key-to-finding-the-ultimate
	ability to colaborate with others, and potential for growth and development.
	
- cultural se moze staviti umesto culture --> what-is-the-key-to-finding-the-ultimate
	sitant to bring up any culture queries you may have durin
	
- ne treba the ispred abundant --> what-does-a-rebranding-process-include-beside-a-new-logo
	together after the abundant planning, research, figuring out 
	
- Ne treba had moze da se obrise	-->  what-does-a-rebranding-process-include-beside-a-new-logo
	we had gathered public opinion through 
	
- the treba dodati ispred positive -->what-does-a-rebranding-process-include-beside-a-new-logo
	The other distinctive part was positive aspects, things that answered 
	
- The treba dodati ispred Design i crowd treba sa velikim C	-->what-does-a-rebranding-process-include-beside-a-new-logo
	a new logo on Design crowd platform.
	
- had to include pre :, zatim types o graphics that should be used --> what-does-a-rebranding-process-inc
	In addition, those also had to be included: brand’s archetype, tone, voice, fonts, usage of typography and logo, mood board with photos, and types of graphic which should be used.
	
- wanted treba umesto want --> what-does-a-rebranding-process-include-beside-a-new-logo
	which platforms we want our brand to be present on
	
- Ne treba da zarez iza platforms --> what-does-a-rebranding-process-include-beside-a-new-logo
	profiles on social media and job searching platforms, and brought our 
	
- 	the treba da se doda ispred company --> how-to-build-a-culture-that-matches-your-brand
	from how we interact with one another and our clients to the layout of our meeting rooms and company’s website
	
- Ne treba zarez iza survive --> how-to-build-a-culture-that-matches-your-brand
	team to not just survive, but to thrive in

- beanbags treba da se stavi --> how-to-build-a-culture-that-matches-your-brand
	leasant meeting space with colorful wallpaper, beenbags and armchairs.

- Ne mora zarez iza --> how-to-build-a-culture-that-matches-your-brand
	ame beliefs and backgrounds, but share

- Cherished ide sa jednim r	--> careers
	Cherrished employee is the best employee

- the treba ispred qa team --> automated-quality-assurance-qa-engineer
	Support and contribute to QA team by sharing best practices

- The ispred developer i the ispred root --> automated-quality-assurance-qa-engineer
	View log files, understand them and assist developer in finding root cause of the bug

- a treba da ide ispred minimum --> javascript-frontend-software-developer
	At least a few years of relevant industry experience or minimum of BSC from a computer science university

- ne treba a ispred co-founder --> contact --> Partnerships
	Tibor Dudjik As our main advisor and a co‑founder, Tibor plays a crucial role in our 
	
- Internet treba veliko I --> privacy-policy
	However, please note that no method of transmission over the internet or electronic storage is 100% secure, and we cannot guarantee absolute security.

- Firefox dugo f ide malo --> accessibility-statement
	The ALAS doo website is designed to be compatible with assistive technologies and the last two versions of major browsers including Chrome, FireFox, and Safari.
