### ISSUE TITLE
When skip link is activated on some pages the heading is partially covered by the header

### ISSUE THREAD

**Issue by Tajana-Somogyi** [ALASdoo/alasdoo_com_v2#147]
On the following pages:

- [x] Our story
- [x] Case studies
- [x] Careers
- [x] Articles
- [x] Contact us
- [x] Cookies
- [x] Privacy Policy

- [x] Connected issue: For Cookies and Privacy policy spacing should olso be modified and made consistent throughout the page
- [x] https://github.com/ALASdoo/alasdoo_com_v2/issues/149
- [ ] @nemain00 Check this issue on smaller screens for other pages

**Comment by TheKolega** [comment]
Looks good :green_circle:, tested on smaller screens as well
