### ISSUE TITLE
No alt text for checkmark in job ad form

### ISSUE THREAD

**Issue by Tajana-Somogyi** [ALASdoo/alasdoo_com_v2#148]
<img width="948" alt="Screenshot 2024-11-15 at 22 12 28" src="https://github.com/user-attachments/assets/372e1fb4-f160-4163-afab-dc8790b84f0e">

**Comment by Tajana-Somogyi** [comment]
- [ ] Add alt text (or aria-label): "Valid document format"

**Comment by TheKolega** [comment]
Looks good :green_circle:
