### ISSUE TITLE
Privacy policy not associated with Send Message button

### ISSUE THREAD

**Issue by Tajana-Somogyi** [ALASdoo/alasdoo_com_v2#174]
- [x] Change privacy policy text to: "We only use your personal information to respond to your inquiry. By submitting this form, you agree to our [Privacy Policy](https://deploy-preview-22--alasdoo.netlify.app/privacy-policy)."
- [x] Link the privacy policy text to the form or submit button using aria-describedby. Example:
<p id="privacy-policy">We only use your personal information to respond to your inquiry. By submitting this form, you agree to our <a href="/privacy-policy">Privacy Policy</a>.</p>
    <button type="submit" aria-describedby="privacy-policy">Submit</button>

- [x] change Send Message button label to "Send message" to be consistent with sentence case

- [x] do the same changes for job ads

**Comment by TheKolega** [comment]
Looks good :green_circle:

**Comment by Tajana-Somogyi** [comment]
We'll add a checkbox for more predictable UI
