### ISSUE TITLE
There is no file format restriction message and the user is able to attach and send any format of the file

### ISSUE THREAD

**Issue by Qtester94** [ALASdoo/alasdoo_com_v2#18]
**Steps to reproduce:**
- Open the https://alas-v2.netlify.app/ page
- Click on the "Contact Us" button
- Click on the "Careers" top navigation option
- Scroll down to the "Current job openings"
- Click on any job card
- Fill all the fields 
- Notice that there is a message that "doc or pdf files, up to 2MB"
- Click on the "Choose File" button
- Choose a png file
- Notice that the png file can be attached 
- Click on the "Choose File" button
- Choose a jpg file
- Notice that the jpg file can be attached
- Click on the "Choose File" button
- Choose the tiff file
- Notice that Tiff file can be attached
- Click on the "Apply Now" button

**Actual error:** There is no file format restriction message and the user is able to attach and send any format of the file.
**Expected fix:**  There should be some error message for file format restriction and the user should not be able to attach and send any file format.

**Noticed on:** Windows 10 - Microsoft Edge 113.0.1774.57

**Screencast:**
https://drive.google.com/file/d/1qiFYYmr9-qTXo_LLDUYGn6Vrls_THTmj/view?usp=drivesdk

**Comment by Qtester94** [comment]
Also, on mobile, the user is able to get pictures with the camera. 
Screencast : https://drive.google.com/file/d/13as4GFhto-blATxpCE2s8Acbun9_pccx/view?usp=drivesdk

**Comment by lsale98** [comment]
Fixed, need to test on real mobile device
