### ISSUE TITLE
"404 Page Not Found" error message is displayed when the user is navigated to the "Cookies" page from the "Analytics cookies only" modal window via link

### ISSUE THREAD

**Issue by nemain00** [ALASdoo/alasdoo_com_v2#180]
![chrome_8sh3SEBezq](https://github.com/user-attachments/assets/2312b883-30a1-40b7-a097-7b689d91b7ec)
![chrome_BJWHmguyTE](https://github.com/user-attachments/assets/9a3872eb-cb5a-4874-9405-71e70752689b)

**Comment by TheKolega** [comment]
Looks good :green_circle:
