### ISSUE TITLE
Mobile: Hamburger menu should close when clicking outside of menu

### ISSUE THREAD

**Issue by janos021** [ALASdoo/alasdoo_com_v2#19]
Steps to reproduce:
- Open https://alas-v2.netlify.app/
- Tap Hamburger menu
- Tap outside of the Hamburger menu

Actual error : Hamburger menu remains open
Expected fix : Hamburger menu should close

Noticed on iPhone11/ iOS 16.0.3 - Safari, Samsung Galaxy 8+/ Android 9 - Chrome

Screencast:
https://drive.google.com/file/d/1DTboAoQNOyA14_BbPn2HbF1fmqi0ELga/view

**Comment by lsale98** [comment]
Fixed
