### ISSUE TITLE
Mobile: Cookie popup responsiveness issues

### ISSUE THREAD

**Issue by janos021** [ALASdoo/alasdoo_com_v2#2]
Steps to reproduce:
- Clear browsers cache
- Open https://alas-v2.netlify.app/
- Check layout
- Alternatively scroll the page 
-
Actual error : Cookie popup isn't formatted correctly, line spacing isn't consistent, elements changing position during scroll
Expected fix : Line spacing should be consistent, elements fixed

Noticed on iPhone11/iOS 16.03 - Safari, Samsung Galaxy8+/Android 9, Chrome and Samsung Galaxy8+/Android 9, Firefox

Screenshot:https://drive.google.com/file/d/1xpQsywlwtyXjLNRDfsxwdlCQeDEuEOTE/view
Screencast:https://drive.google.com/file/d/175f3tpPcIXYeVNKmZzls289ilg43cwUw/view

**Comment by lsale98** [comment]
Fixed
