### ISSUE TITLE
The "Other Jobs" section always contains the same job cards

### ISSUE THREAD

**Issue by Qtester94** [ALASdoo/alasdoo_com_v2#20]
**Steps to reproduce:**
- Open the https://alas-v2.netlify.app/ page
- Click on the "Careers" top navigation option
- Scroll down to the "Current job openings" section
- Click on the "Automated QA Engineer" job card
- Check the "Other Jobs" section
- Notice that the "Automated QA Engineer" is listed in the "Other Jobs" section 
- Click on any job card
- Check the "Other Jobs" section

**Actual error:** The "Other Jobs" section always contains the same job cards.
**Expected fix:** The "Other Jobs" section should contain different jobs than it was selected, the section should be filled up dynamically.

**Noticed on:** Windows 10 - Microsoft Edge 113.0.1774.57

**Screencast:**
https://drive.google.com/file/d/1ZfE3F7O8GGhV9Th1ygLp-7K8Xiyv_zbR/view?usp=drivesdk

**Comment by lsale98** [comment]
Fixed
