### ISSUE TITLE
Bug: List bullets not showing when high contrast mode is enabled 

### ISSUE THREAD

**Issue by a-kosanovic** [ALASdoo/alasdoo_com_v2#216]
![image](https://github.com/user-attachments/assets/030ff67d-917e-4b48-b9d7-8d4999c1b666)

- expected: show native list bullets in primary colour: 
![Screenshot from 2024-12-02 14-49-07](https://github.com/user-attachments/assets/9aead674-849c-4da9-be03-7835375b8825)

- enable high contrast mode: 
![Screenshot from 2024-12-02 14-50-23](https://github.com/user-attachments/assets/2db8ee11-89d2-4599-9bea-5b7d8838c4cd)

**Comment by Tajana-Somogyi** [comment]
hanged to native ones with our color
