### ISSUE TITLE
Add following keywors for SEO

### ISSUE THREAD

**Issue by a-kosanovic** [ALASdoo/alasdoo_com_v2#227]
Keywords: 
-  quality assurance
- software testing
- software engineers
- software developer
- information technology
- web accessibility
- website accessibility audit
- project management

Description:
Optimize software development with ALAS expert IT outsourcing: development, testing, and accessibility solutions.

Title: 
`ALAS doo: Digital excellence in development, testing & accessibility`

**Comment by Tajana-Somogyi** [comment]
Title is not changed
