### ISSUE TITLE
Cookies modal image alt text shouldnt contain word "...image"

### ISSUE THREAD

**Issue by TheKolega** [ALASdoo/alasdoo_com_v2#237]
This is triggering the Wave alert on `Suspicious alternative text`. As screen readers already announce when something is an image, this is extraneous data.

I suggest setting the alt text to blank so screen readers would skip it, as this isnt relevant data, or changing it to "Cookie settings modal" or some variation of such, to act as a header description

**Comment by vsomogyi** [comment]
Set to empty alt.
