### ISSUE TITLE
Cookie Modal

### ISSUE THREAD

**Issue by a-kosanovic** [ALASdoo/alasdoo_com_v2#27]
- [ ]  The cookie modal should appear on the user's first visit to the website regardless which page the user navigates to 
- [ ]  User's preferences (accept/decline) cookies should be stored for max of 30 days after which cookie modal is shown again 
- [ ]  Clicking on the Decline button or the space outside the modal - closes modal and prevents cookies 
- [ ]  No cookies should be set before the user clicks on the Accept button 
- [ ]  scripts added when user clicks Accept button 
- [ ]  page should be `inert` when modal is open (user cannot scroll or interact with the page behind, screen reader cannot read it) 
- [ ]  modal sho

---
- **Resources**
  - ![image](https://github.com/user-attachments/assets/dc9aaae7-a4f9-43f7-a614-3200e7edae0c)
  - Illustration: https://drive.google.com/file/d/13cPgHgQ7Q5LZT8vjVIovoObGbmmXyP_S/view?usp=drive_link

**Comment by Tajana-Somogyi** [comment]
Remove "close" button and tooltip
