### ISSUE TITLE
FB sharer doesn't work on desktop on "Current job openings"

### ISSUE THREAD

**Issue by janos021** [ALASdoo/alasdoo_com_v2#3]
Steps to reproduce:
- Open https://alas-v2.netlify.app/career/
- Click on any position ( eg Automated QA engineer )
- Click  on FB icon on Share this job:

Actual error:  Sorry, something went wrong error is shown
Expected fix : Share to facebook feed should open if the user is logged in in the same browser, or prompted to log in Facebook if not logged in

Note: the sharer works only mobile devices where the user is logged in Facebook app

Noticed on  : 
Windows 10, Google Chrome 113.0.5672.127

Screencast: 
https://drive.google.com/file/d/1jiPxBxJqLspckh5shGn6jpKhw0jfh2LJ/view

**Comment by lsale98** [comment]
Based on Vilmos's input, we'll remove share job option
