### ISSUE TITLE
Edge: The picture is not loaded on the "What we do" pages 

### ISSUE THREAD

**Issue by Qtester94** [ALASdoo/alasdoo_com_v2#4]
**Steps to reproduce:**
- Open the https://alas-v2.netlify.app/ page
- Click on the "What we do" top navigation option
- Check if images appear

**Actual error:** The images are not loaded on the page.
**Expected fix:** The images should load

**Noticed on:** Windows 10 - Microsoft Edge 113.0.1774.57

**Screencast:**
https://drive.google.com/file/d/1JHbQSRLkFZqxFnAxq-MWHrU3ST8ZJQHl/view?usp=drivesdk

**Comment by lsale98** [comment]
Fixed
