### ISSUE TITLE
The picture is not loaded on the "Clients" pages 

### ISSUE THREAD

**Issue by Qtester94** [ALASdoo/alasdoo_com_v2#5]
**Steps to reproduce:**
- Open the https://alas-v2.netlify.app/ page
- Click on the "Who we are" top navigation option
- Click on the "Clients" dropdown option
- Check if the image appears

**Actual error:** The images are not loaded on the page.
**Expected fix:** The images should load

**Noticed on:** Windows 10 - Microsoft Edge 113.0.1774.57

Note: The same issue is present on Mozilla Firefox

**Screencast:**
https://drive.google.com/file/d/1dxhdrRDe5JRnlw6lEUdLigScJkrxPQ9J/view?usp=drivesdk
https://drive.google.com/file/d/1sXmvOmdtRPJL5p_jGF66O9iHdafsLESZ/view?usp=drivesdk

**Comment by lsale98** [comment]
Fixed
