### ISSUE TITLE
Firefox: The picture is not loaded on the "What we do" page's second paragraph

### ISSUE THREAD

**Issue by Qtester94** [ALASdoo/alasdoo_com_v2#6]
Steps to reproduce:
- Open the https://alas-v2.netlify.app/ page
- Click on the "What we do" top navigation option
- Scroll to the second paragraph
- Check if the image appears

Actual error: The images are not loaded on the page.
Expected fix: The images should load

Noticed on: Windows 10 - Mozilla Firefox 113.0.2

Screencast:
https://drive.google.com/file/d/1eIg7JTIg05HlUeBdBSLgAvnjJgZ2jWBl/view?usp=drivesdk

**Comment by lsale98** [comment]
Works properly on Linux and Mac. Still need to check on windows
