### ISSUE TITLE
Add support for prefers-reduced-motion 

### ISSUE THREAD

**Issue by a-kosanovic** [ALASdoo/alasdoo_com_v2#68]
Animations should be disabled if customer has `prefers-reduced-motion` settings enabled in browser 

Resources: 
- https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
- ![image](https://github.com/user-attachments/assets/ab5a1153-0a79-4b6c-9126-fb3573137a97)

**Comment by Tajana-Somogyi** [comment]
Relates to issues #36 and #162

**Comment by Tajana-Somogyi** [comment]
@a-kosanovic Fix animation blur of hediongs on cards (and possibly buttons)
