### ISSUE TITLE
Safari: The space between paragraphs is much bigger in Safari than in other Browsers on the "What we do" page

### ISSUE THREAD

**Issue by Qtester94** [ALASdoo/alasdoo_com_v2#9]
**Steps to reproduce:**
- Open the https://alas-v2.netlify.app/ page
- Click on the "What we do" top navigation option
- Scroll down
- Check the space between paragraphs

**Actual error:** The space between paragraphs is much bigger in Safari than in other Browsers on the "What we do" page.
**Expected fix:** The space between paragraphs should be smaller.

**Noticed on:** macOS Ventura 13.3.1 - Safari 16.4

**Screencast:**
https://drive.google.com/file/d/1PF34yi-6uwpNWoBZ7n44ytLVmJ5G99Gs/view?usp=drivesd

**Comment by lsale98** [comment]
Fixed, need to check on windows devices
